name: PR Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]

    - name: Run ruff lint
      run: ruff check

    - name: Run mypy type check
      run: mypy . --ignore-missing-imports --exclude tests/ --exclude scripts/

    - name: Run pytest
      run: pytest tests/ -v --tb=short
      env:
        PYTHONHASHSEED: 0
